appConfig:
  theme: nord
  customColors:
    material-dark-original:
      primary: '#f36558'
      background: '#39434C'
      background-darker: '#eb615c'
      material-light: '#f36558'
      item-text-color: '#ff948a'
      curve-factor: 5px
  enableErrorReporting: true
  layout: auto
  iconSize: medium
  language: en
  enableFontAwesome: true
  routingMode: hash
  webSearch:
    disableWebSearch: false
    searchEngine: google
    openingMethod: modal
    searchBangs: {}
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 0
  faviconApi: allesedv
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
pageInfo:
  title: Homelab
  description: links for homelab
  footerText: ''
sections:
  - name: Network
    icon: fas fa-network-wired
    items:
      - title: OpenWRT
        icon: hl-openwrt
        url: https://192.168.1.1
        id: 0_746_openwrt
      - title: UniFi dashboard
        icon: hl-unifi
        url: https://192.168.1.166:8443/
        id: 1_746_unifidashboard
  - name: App Servers
    icon: fas fa-server
    items:
      - title: App Server
        icon: hl-portainer
        url: https://192.168.1.201:9443/
        id: 0_1067_appserver
      - title: Basic Infrastructure
        icon: hl-portainer
        url: https://192.168.1.166:9443/
        id: 1_1067_basicinfrastructure
  - name: Virtualization / Infrastructure
    icon: fas fa-database
    items:
      - title: PVE embedded
        icon: hl-proxmox
        url: https://pve-embedded.localdomain:8006/
        provider: Proxmox
        id: 0_3125_pveembedded
      - title: PVE small
        icon: hl-proxmox
        url: https://192.168.1.42:8006/
        provider: Proxmox
        id: 1_3125_pvesmall
      - title: PVE big
        icon: hl-proxmox
        url: https://192.168.1.40:8006/
        id: 2_3125_pvebig
      - title: Proxmox Backup Server
        icon: hl-proxmox
        url: https://192.168.1.202:8007/
        provider: Proxmox
        id: 3_3125_proxmoxbackupserver
      - title: True NAS
        icon: hl-truenas
        url: https://192.168.1.238/
        id: 4_3125_truenas
      - title: Pi KVM
        icon: hl-pikvm
        url: http://pikvm.localdomain/
        id: 5_3125_pikvm
  - name: Applications
    icon: fas fa-folder-plus
    items:
      - title: Home Assistant
        icon: hl-home-assistant
        url: http://192.168.1.189:8123/
        id: 0_1255_homeassistant
      - title: Photo Prism
        icon: hl-photoprism
        url: http://192.168.1.201:2342/browse
        id: 1_1255_photoprism
      - title: syncthing
        icon: hl-syncthing
        url: http://192.168.1.201:8384/
        id: 2_1255_syncthing
      - title: PiHole 1
        icon: hl-pihole
        url: http://192.168.1.170/admin/
        id: 3_1255_pihole
      - title: PiHole 2
        icon: hl-pihole
        url: http://192.168.1.171/admin/
        id: 4_1255_pihole
      - title: HiFiberry
        icon: fab fa-raspberry-pi
        url: http://hifiberry.localdomain/
        id: 5_1255_hifiberry
      - title: Youtube-DL
        icon: hl-youtube
        url: http://192.168.1.201:8998/#/home
        id: 6_1255_youtubedl
