appConfig:
  theme: nord
  customColors:
    material-dark-original:
      primary: '#f36558'
      background: '#39434C'
      background-darker: '#eb615c'
      material-light: '#f36558'
      item-text-color: '#ff948a'
      curve-factor: 5px
  enableErrorReporting: true
  layout: vertical
  iconSize: medium
  language: en
  enableFontAwesome: true
  routingMode: hash
  webSearch:
    disableWebSearch: false
    searchEngine: google
    openingMethod: modal
    searchBangs: {}
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 0
  faviconApi: allesedv
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
pageInfo:
  title: Homelab
  description: links for homelab
  navLinks: []
  footerText: ''
sections:
  - name: Network
    icon: fas fa-network-wired
    items:
      - &ref_0
        title: OPNsense
        icon: hl-opnsense
        url: https://192.168.1.1
        id: 0_746_opnsense
      - &ref_1
        title: UniFi dashboard
        icon: hl-unifi
        url: https://192.168.1.166:8443/
        id: 1_746_unifidashboard
      - &ref_2
        title: PiHole 1
        icon: hl-pihole
        url: http://192.168.1.171/admin/
        id: 2_746_pihole
      - &ref_3
        title: PiHole 2
        icon: hl-pihole
        url: http://192.168.1.172/admin/
        id: 3_746_pihole
    displayData:
      sortBy: default
      rows: 3
      cols: 1
      collapsed: false
      hideForGuests: false
    filteredItems:
      - *ref_0
      - *ref_1
      - *ref_2
      - *ref_3
  - name: App Servers
    icon: fas fa-server
    items:
      - &ref_4
        title: Basic Infrastructure
        icon: hl-portainer
        url: https://192.168.1.166:9443/
        id: 0_1067_basicinfrastructure
      - &ref_5
        title: single node rancher
        icon: hl-rancher
        url: https://docker-server-v2.localdomain
        id: 1_1067_singlenoderancher
      - &ref_6
        title: homelab rancher
        icon: hl-rancher
        url: https://rancher.localdomain
        id: 2_1067_homelabrancher
    filteredItems:
      - *ref_4
      - *ref_5
      - *ref_6
  - name: Virtualization / Infrastructure
    icon: fas fa-database
    items:
      - &ref_7
        title: PVE Hyper
        icon: hl-proxmox
        url: https://pve-hyper.localdomain:8006
        id: 0_3125_pvehyper
      - &ref_8
        title: PVE small
        icon: hl-proxmox
        url: https://192.168.1.42:8006/
        provider: Proxmox
        id: 1_3125_pvesmall
      - &ref_9
        title: PVE big
        icon: hl-proxmox
        url: https://192.168.1.40:8006/
        id: 2_3125_pvebig
      - &ref_10
        title: True NAS
        icon: hl-truenas
        url: https://192.168.1.39:444
        id: 3_3125_truenas
      - &ref_11
        title: Truenas - backup
        icon: hl-truenas
        url: http://192.168.1.37/
        provider: truenas
        id: 4_3125_truenasbackup
      - &ref_12
        title: PBS - Main
        icon: hl-proxmox
        url: https://192.168.1.127:8007/
        provider: Proxmox
        id: 5_3125_pbsmain
      - &ref_13
        title: PBS - Alt
        icon: hl-proxmox
        url: https://192.168.1.31:8007/
        provider: Proxmox
        id: 6_3125_pbsalt
      - &ref_14
        title: Pi KVM
        icon: hl-pikvm
        url: http://pikvm.localdomain/
        id: 7_3125_pikvm
      - &ref_15
        title: Compute Node KVM
        icon: hl-mikrotik
        url: http://192.168.1.11
        id: 8_3125_computenodekvm
    filteredItems:
      - *ref_7
      - *ref_8
      - *ref_9
      - *ref_10
      - *ref_11
      - *ref_12
      - *ref_13
      - *ref_14
      - *ref_15
  - name: Applications
    icon: fas fa-folder-plus
    items:
      - &ref_16
        title: HiFiberry
        icon: fab fa-raspberry-pi
        url: http://192.168.1.10
        id: 0_1255_hifiberry
      - &ref_17
        title: Home Assistant
        icon: hl-home-assistant
        url: http://192.168.1.163:8123/
        id: 1_1255_homeassistant
      - &ref_18
        title: Nextcloud
        icon: hl-nextcloud
        url: http://192.168.1.202
        id: 2_1255_nextcloud
      - &ref_19
        title: Youtube-DL
        icon: hl-youtube
        url: http://192.168.1.201
        id: 3_1255_youtubedl
    filteredItems:
      - *ref_16
      - *ref_17
      - *ref_18
      - *ref_19
