# yaml-language-server: $schema=https://raw.githubusercontent.com/Lissy93/dashy/master/src/utils/ConfigSchema.json

pageInfo:
  title: Work Service Monitoring
  footerText: ''

sections:
  - name: Prod service urls
    icon: fas fa-link
    displayData: &datagroup
      sortBy: alphabetical
      cols: 1
    items:
      - title: identity-bridge
        icon: fas fa-external-link-alt

  - name: Staging service urls
    icon: fas fa-link
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-external-link-alt
        url: https://identity-bridge-staging.qa.spoton.sh/docs
        
  - name: Staging logs
    icon: fas fa-dog
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-dog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Aidentity-bridge
  
  - name: Prod logs
    icon: fas fa-dog
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-dog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Aidentity-bridge
