# yaml-language-server: $schema=https://raw.githubusercontent.com/Lissy93/dashy/master/src/utils/ConfigSchema.json
appConfig:
  theme: nord
  customColors:
    material-dark-original:
      primary: '#f36558'
      background: '#39434C'
      background-darker: '#eb615c'
      material-light: '#f36558'
      item-text-color: '#ff948a'
      curve-factor: 5px
  enableErrorReporting: true
  layout: auto
  iconSize: medium
  language: en
  enableFontAwesome: true
  routingMode: hash


x-display-data: &datagroup
    sortBy: alphabetical
    cols: 1

pageInfo:
  title: Work Service Monitoring
  footerText: ''

sections:
  - name: Monitoring
    icon: fas fa-network-wired
    items:
      - title: core-services clickboard
        icon: fas fa-dog
        url: >-
          https://app.datadoghq.com/dashboard/ga9-46m-hq2/clickboard-core?from_ts=1663700105960&to_ts=1663703705960&live=true
  
  - name: Infrastructure
    icon: fas fa-digital-tachograph
    items:
      - title: AWS account switcher
        icon: fa-database
        url: 'https://d-90676ae83d.awsapps.com/start#/'

    # service monitoring
  - name: Prod service urls
    icon: fas fa-link
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-external-link-alt
  - name: Prod logs
    icon: fas fa-dog
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-dog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Aidentity-bridge

  - name: Staging service urls
    icon: fas fa-link
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-external-link-alt
        url: https://identity-bridge-staging.qa.spoton.sh/docs
        
  - name: Staging logs
    icon: fas fa-dog
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-dog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Aidentity-bridge
  

