# yaml-language-server: $schema=https://raw.githubusercontent.com/Lissy93/dashy/master/src/utils/ConfigSchema.json

pageInfo:
  title: Spoton
  description: Links for work
  footerText: ''

sections:
  - name: Monitoring
    icon: fas fa-network-wired
    items:
      - title: core-services clickboard
        icon: fas fa-dog
        url: >-
          https://app.datadoghq.com/dashboard/ga9-46m-hq2/clickboard-core?from_ts=1663700105960&to_ts=1663703705960&live=true
            

  - name: Prod service urls
    icon: fas fa-link
    displayData: &datagroup
      sortBy: alphabetical
      cols: 1
    items:
      - title: identity-bridge
        icon: fas fa-external-link-alt

  - name: Staging service urls
    icon: fas fa-link
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-external-link-alt
        url: https://identity-bridge-staging.qa.spoton.sh/docs
        
  - name: Staging logs
    icon: fas fa-dog
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-dog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Aidentity-bridge
  
  - name: Prod logs
    icon: fas fa-dog
    displayData: *datagroup
    items:
      - title: identity-bridge
        icon: fas fa-dog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Aidentity-bridge
