# yaml-language-server: $schema=https://raw.githubusercontent.com/Lissy93/dashy/master/src/utils/ConfigSchema.json

pageInfo:
  title: Spoton Service Monitoring
  footerText: ''

sections:
  - name: identity-bridge
    items:
      - title: staging url
        icon: fas fa-external-link-alt
        url: https://app.datadoghq.com/u?source=hyperlink&target=https%3A%2F%2Fidentity-bridge-staging.qa.spoton.sh%2Fdocs&author=datadog-user&hash=3VSNE6j%2B%2BD5s6uW76XzHrDGyB47LHXE3ixRaauaBO%2Bg%3D
        
      - title: prod url
        icon: fas fas fa-external-link-alt
      
      - title: staging logs
        icon: fas fa-dog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Aidentity-bridge


      - title: prod logs
        icon: fas fa-dog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Aidentity-bridge