# yaml-language-server: $schema=https://raw.githubusercontent.com/Lissy93/dashy/master/src/utils/ConfigSchema.json
appConfig:
  theme: nord
  customColors:
    material-dark-original:
      primary: '#f36558'
      background: '#39434C'
      background-darker: '#eb615c'
      material-light: '#f36558'
      item-text-color: '#ff948a'
      curve-factor: 5px
  enableErrorReporting: true
  layout: auto
  iconSize: medium
  language: en
  enableFontAwesome: true
  routingMode: hash


x-display-data: &datagroup
    sortBy: alphabetical
    cols: 1

pageInfo:
  title: Work Links
  footerText: ''
  navLinks:
    - title: Homelab
      path: 'http://docker-server-v2.localdomain:5000/'

sections:
  - name: Tools
    icon: fas fa-network-wired
    items:
      - title: CSVC Jira
        icon: si-jira
        url: https://spotonteam.atlassian.net/jira/software/c/projects/CSVC/boards/248

      - title: Acronym Glosssary
        icon: si-confluence
        url: https://spotonteam.atlassian.net/wiki/spaces/EM/pages/1990197323/Acronyms+Glossary+Dictionary

      - title: Metabase
        icon: si-metabase
        url: https://metabase.us-east-1.data.spoton.sh/dashboard/375-merchant-landscape?status=Active&status=Pending%20Active&status=Pre-Cancellation

  - name: HR
    items:
      - title: concur
        icon: si-concur
        url: https://www.concursolutions.com/nui/signin?targetURL=%2Fhome 

      - title: ADP
        icon: fa fa-person-simple
        url: https://online.adp.com/signin/v1/?APPID=WFNPortal&productId=80e309c3-7085-bae1-e053-3505430b5495&returnURL=https://workforcenow.adp.com/&callingAppId=WFN&TARGET=-SM-https://workforcenow.adp.com/theme/index.html 
  
      - title: Lattice
        icon: si-lattice
        url: https://spoton.latticehq.com/

  - name: Infrastructure
    icon: fas fa-digital-tachograph
    items:
      - title: AWS account switcher
        icon: si-amazon
        url: 'https://d-90676ae83d.awsapps.com/start#/'

      - title: Staging k8s
        icon: si-kubernetes
        url: https://dashboard.us-east-1.staging.spoton.sh/#/overview?namespace=default
        tags:
          - kubernetes
      - title: Prod k8s
        icon: si-kubernetes
        url: https://dashboard.us-east-1.prod.spoton.sh/#/overview?namespace=default
        tags:
          - kubernetes
      
      - title: Codefresh
        icon: si-hellofresh
        url: https://g.codefresh.io/projects/

      - title: core-services clickboard
        icon: si-datadog
        url: >-
          https://app.datadoghq.com/dashboard/ga9-46m-hq2/clickboard-core?from_ts=1663700105960&to_ts=1663703705960&live=true

  - name: HR
    items:
      - title: concur
        icon: si-concur
        url: https://www.concursolutions.com/nui/signin?targetURL=%2Fhome 

      - title: ADP
        icon: fa fa-person-simple
        url: https://online.adp.com/signin/v1/?APPID=WFNPortal&productId=80e309c3-7085-bae1-e053-3505430b5495&returnURL=https://workforcenow.adp.com/&callingAppId=WFN&TARGET=-SM-https://workforcenow.adp.com/theme/index.html 
  
      - title: Lattice
        icon: si-lattice
        url: https://spoton.latticehq.com/

    # service monitoring
  - name: Prod service urls
    icon: fas fa-link
    displayData: *datagroup
    items:
      - title: core-login-app
        icon: fas fa-external-link-alt
        url: https://login.spoton.com/home/
      
      - title: dishout-service
        icon: fas fa-external-link-alt
        url: https://dishout-service-prod.us-east-1.prod.spoton.sh/docs
      
      - title: e-gift-config-api
        icon: fas fa-external-link-alt
        url: https://egift-config-api-prod.us-east-1.prod.spoton.sh/docs
      
      - title: identity-bridge
        icon: fas fa-external-link-alt
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Aidentity-bridge
      
      - title: merchant-data-service
        icon: fas fa-external-link-alt
        url: https://merchant-data-service-prod.us-east-1.prod.spoton.sh/docs

      - title: notification-service
        icon: fas fa-external-link-alt
        url: https://notification-service-prod.us-east-1.prod.spoton.sh/docs
      
      - title: notification-service
        icon: fas fa-external-link-alt
        url: https://notification-service-prod.us-east-1.prod.spoton.sh/docs
      
      - title: payment-stats-service
        icon: fas fa-external-link-alt
        url: ''
      
      - title: payroll-service
        icon: fas fa-external-link-alt
        url: https://payroll-service-prod.us-east-1.prod.spoton.sh/docs
  
  - name: Prod logs
    icon: si-datadog
    displayData: *datagroup
    items:
      - title: auth-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Aauth-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1663870119765&to_ts=1663871019765&live=true
      
      - title: core-login-app
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%253Aprod%20service%253Acore-login-app      
      
      - title: dishout-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Adishout-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1663870197720&to_ts=1663871097720&live=true      
      
      - title: e-gift-config-api
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%253Aprod%20service%253Aegift-config-api
      
      - title: identity-bridge
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Aidentity-bridge
      
      - title: merchant-data-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Amerchant-data-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1663870284770&to_ts=1663871184770&live=true
      
      - title: merchant-data-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Anotification-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1663870424067&to_ts=1663871324067&live=true

      - title: notification-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Anotification-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1663870697625&to_ts=1663871597625&live=true
      
      - title: payment-stats-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Aprod%20service%3Apayment-stats-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1663870724075&to_ts=1663871624075&live=true

      - title: payroll-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%253Aprod%20service%253Apayroll-service
  - name: Staging service urls
    icon: fas fa-link
    displayData: *datagroup
    items:
      - title: auth-service
        icon: fas fa-external-link-alt
        url: https://auth-service-staging.qa.spoton.sh/
      
      - title: core-login-app
        icon: fas fa-external-link-alt
        url: https://qa-login.spoton.com/home/
      
      - title: dishout-service
        icon: fas fa-external-link-alt
        url: https://dishout-service-staging.qa.spoton.sh/docs
        
      - title: e-gift-config-api
        icon: fas fa-external-link-alt
        url: https://egift-config-api-staging.qa.spoton.sh/docs

      - title: identity-bridge
        icon: fas fa-external-link-alt
        url: https://identity-bridge-staging.qa.spoton.sh/docs
      
      - title: merchant-data-service
        icon: fas fa-external-link-alt
        url: https://merchant-data-service-staging.qa.spoton.sh/docs
      
      - title: notification-service
        icon: fas fa-external-link-alt
        url: https://notification-service-staging.qa.spoton.sh/docs

      - title: payment-stats-service
        icon: fas fa-external-link-alt
        url: https://payment-stats-service-staging.qa.spoton.sh/docs
      
      - title: payment-stats-service
        icon: fas fa-external-link-alt
        url: https://payroll-service-staging.qa.spoton.sh/docs
        
  - name: Staging logs
    icon: si-datadog
    displayData: *datagroup
    items:
      - title: auth-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Aauth-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1663871072422&to_ts=1663871972422&live=true
        
      - title: core-login-app
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Aauth-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1663871072422&to_ts=1663871972422&live=true
        
      - title: dishout-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Adishout-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1663871134745&to_ts=1663872034745&live=true
        
      - title: e-gift-config-api
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Aegift-config-api

      - title: merchant-data-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Amerchant-data-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1663871183633&to_ts=1663872083633&live=true

      - title: notification-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Anotification-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1663871200816&to_ts=1663872100816&live=true        

      - title: payment-stats-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Astaging service%3Apayment-stats-service&cols=host%2Cservice&index=*&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1663871239393&to_ts=1663872139393&live=true
      
      - title: payroll-service
        icon: si-datadog
        url: https://app.datadoghq.com/logs?query=env%3Astaging%20service%3Apayroll-service&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1663871274269&to_ts=1663872174269&live=true
